language: java

install:
  - mkdir -p ~/.ant/lib && ln -s -T /usr/share/java/ivy.jar ~/.ant/lib/ivy.jar
  - sh scripts/ci-init.sh

script:
  - ant resolve-ivy-deps
  - ant jar

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  apt:
    packages:
      - python3

matrix:
  allow_failures:
    - jdk: oraclejdk7
    - jdk: openjdk7
